dcache-webdav: fixed bug in TLS handshake for webdav with https introduced in the commit a8edc2642417aee14ae7944956d5fdedc2cfee1b
Webdav with https was failing because the TLS Handshake was failing.

java.io.IOException: Request with requestId =-2147482639 rs.state =
Failed rs.error = Waiting for transfers to complete.
RequestFileStatus#-2147482638 failed with error:[  at Wed Jan 13
08:54:12 CET 2016 state Failed : Transfer failed: remote server rejected
GET: 500 Server Error]

https://localhost:2881/disk/test-1452671619-38/d ->
srm://localhost:8443/disk/test-1452671619-38/e: copy failedWaiting for
transfers to complete. RequestFileStatus#-2147482638 failed with error:[
at Wed Jan 13 08:54:12 CET 2016 state Failed : Transfer failed: remote
server rejected GET: 500 Server Error]

Failed with exit code pid 29060 exit 1

Ticket:
Acked-by:
Target: trunk
Require-book: no
Require-notes: no
Patch: